# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='projects', verbose_name='Imagen')),
                ('titulo', models.CharField(max_length=255, verbose_name='T\xedtulo')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Direcci\xf3n Web')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousel',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.TextField()),
                ('publicacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publicacion'],
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Destacado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('link', models.URLField(verbose_name='Direcci\xf3n Web')),
            ],
            options={
                'verbose_name': 'Destacado',
                'verbose_name_plural': 'Destacados',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='projects', verbose_name='Imagen')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Direcci\xf3n Web')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Social',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('titulo', models.CharField(max_length=255, verbose_name='T\xedtulo')),
                ('operacion', models.CharField(max_length=255, verbose_name='Operaci\xf3n')),
                ('dormitorios', models.IntegerField(verbose_name='Dormitorios')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('superficie', models.IntegerField(verbose_name='Superficie')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicaci\xf3n')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('banos', models.IntegerField(verbose_name='Ba\xf1os')),
                ('imagen', models.ImageField(upload_to='projects', verbose_name='Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
                ('antiguedad', models.DateField(max_length=255, verbose_name='Antig\xfcedad')),
                ('publicacion', models.DateField(default=django.utils.timezone.now, verbose_name='Publicaci\xf3n')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Direcci\xf3n Web')),
            ],
            options={
                'ordering': ['-publicacion'],
                'verbose_name': 'Vivienda',
                'verbose_name_plural': 'Viviendas',
            },
        ),
    ]
