# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destacado',
            name='link',
        ),
        migrations.AddField(
            model_name='destacado',
            name='identificador',
            field=models.IntegerField(default=0, verbose_name='Identificador de Vivienda destacada'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='destacado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='destacado',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='social',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
