# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='projects', verbose_name='Imagen')),
                ('titulo', models.CharField(max_length=255, verbose_name='T\xedtulo')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Direcci\xf3n Web')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousel',
            },
        ),
    ]
