# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0004_auto_20180913_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='imagen',
            field=models.ImageField(upload_to='projects/carousel/', verbose_name='Imagen'),
        ),
    ]
