# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0006_auto_20181001_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='activado',
            field=models.BooleanField(default=True, verbose_name='Activada'),
        ),
    ]
