# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0007_carousel_activado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['-publicacion'], 'verbose_name': 'Carousel', 'verbose_name_plural': 'Carousel'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='publicacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Publicaci\xf3n'),
        ),
    ]
