# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 17:52
from __future__ import unicode_literals

import carousel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0009_auto_20181004_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=carousel.models.custom_upload_to, verbose_name='Imagen'),
        ),
    ]
