# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logotipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logotipo',
            old_name='logotipo',
            new_name='imagen',
        ),
    ]
