# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logotipo', '0002_auto_20181001_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logotipo',
            options={'verbose_name': 'Logotipo', 'verbose_name_plural': 'Logotipos'},
        ),
    ]
