# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import logotipo.models


class Migration(migrations.Migration):

    dependencies = [
        ('logotipo', '0003_auto_20181001_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logotipo',
            name='imagen',
            field=models.ImageField(upload_to=logotipo.models.custom_upload_to, verbose_name='Logotipo'),
        ),
    ]
