# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logotipo', '0004_auto_20181001_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='logotipo',
            name='actualizacion',
            field=models.DateField(auto_now=True, verbose_name='Actualizaci\xf3n'),
        ),
        migrations.AddField(
            model_name='logotipo',
            name='publicacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Publicaci\xf3n'),
        ),
    ]
