# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import logotipo.models


class Migration(migrations.Migration):

    dependencies = [
        ('logotipo', '0006_logotipo_imagen_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logotipo',
            name='imagen',
            field=models.ImageField(upload_to=logotipo.models.custom_upload_to, verbose_name='Logotipo (M\xe1x. 10MB)'),
        ),
        migrations.AlterField(
            model_name='logotipo',
            name='imagen_mobile',
            field=models.ImageField(null=True, upload_to=logotipo.models.custom_upload_to_mobile, verbose_name='Logotipo peque\xf1o (M\xe1x. 10MB)'),
        ),
    ]
