# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 11:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='actualizacion',
            field=models.DateField(auto_now=True, verbose_name='Actualizaci\xf3n'),
        ),
        migrations.AddField(
            model_name='nosotros',
            name='publicacion',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 10, 4, 11, 22, 17, 178000, tzinfo=utc), verbose_name='Publicaci\xf3n'),
            preserve_default=False,
        ),
    ]
