# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False, unique=True, verbose_name='Social_key')),
                ('nombre', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Direcci\xf3n Web')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
    ]
