# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='Social_key'),
        ),
    ]
