# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('contenido', models.TextField(verbose_name='Contenido')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Politica',
                'verbose_name_plural': 'Politicas',
            },
        ),
    ]
