# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicas', '0002_auto_20181004_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='politica',
            name='activado',
            field=models.BooleanField(default=True, verbose_name='Activada'),
        ),
        migrations.AlterField(
            model_name='politica',
            name='contenido',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
