# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('titulo', models.CharField(max_length=255, verbose_name='T\xedtulo')),
                ('operacion', models.CharField(max_length=255, verbose_name='Operaci\xf3n')),
                ('dormitorios', models.IntegerField(verbose_name='Dormitorios')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('superficie', models.IntegerField(verbose_name='Superficie')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicaci\xf3n')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('banos', models.IntegerField(verbose_name='Ba\xf1os')),
                ('imagen', models.ImageField(upload_to='projects', verbose_name='Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
                ('antiguedad', models.DateField(max_length=255, verbose_name='Antig\xfcedad')),
                ('publicacion', models.DateField(default=django.utils.timezone.now, verbose_name='Publicaci\xf3n')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Direcci\xf3n Web')),
                ('altitud', models.CharField(default='None', max_length=255, verbose_name='Altitud')),
                ('latitud', models.CharField(default='None', max_length=255, verbose_name='Latitud')),
                ('eficiencia', models.CharField(default='None', max_length=255, verbose_name='Eficiencia')),
            ],
            options={
                'ordering': ['-publicacion'],
                'verbose_name': 'Vivienda',
                'verbose_name_plural': 'Viviendas',
            },
        ),
    ]
