# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='descripcion',
            field=models.TextField(verbose_name='Descripci\xf3n'),
        ),
    ]
