# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_auto_20180911_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda_gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('imagen_gallery', models.ImageField(upload_to='projects/gallery', verbose_name='Imagen de galer\xeda')),
                ('publicacion', models.DateField(default=django.utils.timezone.now, verbose_name='Publicaci\xf3n')),
            ],
            options={
                'ordering': ['-publicacion'],
                'verbose_name': 'Galer\xeda de vivienda',
                'verbose_name_plural': 'Galer\xedas de viviendas',
            },
        ),
        migrations.AddField(
            model_name='vivienda',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Vivienda destacada'),
        ),
        migrations.AddField(
            model_name='vivienda_gallery',
            name='titulo',
            field=models.ManyToManyField(to='viviendas.Vivienda', verbose_name='T\xedtulo vivienda'),
        ),
    ]
