# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0003_auto_20180913_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda_gallery',
            name='identificador',
            field=models.ManyToManyField(to='viviendas.Vivienda', verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='vivienda_gallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='vivienda_gallery',
            name='titulo',
        ),
        migrations.AddField(
            model_name='vivienda_gallery',
            name='titulo',
            field=models.CharField(default='', max_length=255, verbose_name='T\xedtulo vivienda'),
        ),
    ]
