# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0004_auto_20180916_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda_gallery',
            name='identificador',
        ),
        migrations.AddField(
            model_name='vivienda',
            name='galeria',
            field=models.ManyToManyField(to='viviendas.Vivienda_gallery', verbose_name='Im\xe1genes de galer\xeda'),
        ),
    ]
