# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0005_auto_20180916_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='imagen',
            field=models.ImageField(upload_to='projects/viviendas_imagen', verbose_name='Imagen'),
        ),
    ]
