# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0006_auto_20180916_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='imagen',
            field=models.ImageField(upload_to='projects/viviendas_image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='vivienda_gallery',
            name='imagen_gallery',
            field=models.ImageField(upload_to='http://a06e01c97.appspot.com/media/projects/gallery', verbose_name='Imagen de galer\xeda'),
        ),
    ]
