# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0012_auto_20180924_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda_gallery',
            name='titulo',
            field=models.CharField(default='', max_length=255, verbose_name='T\xedtulo galer\xeda de vivienda'),
        ),
    ]
