# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0013_auto_20180925_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='link',
        ),
    ]
