# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0015_auto_20181001_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='precio',
            field=models.CharField(max_length=255, verbose_name='Precio'),
        ),
    ]
