# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0018_auto_20181003_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
