# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import viviendas.models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0019_auto_20181003_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='planos',
            field=models.FileField(default='', upload_to=viviendas.models.custom_upload_to_planos, verbose_name='Planos de vivienda'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='video',
            field=models.FileField(default='', upload_to=viviendas.models.custom_upload_to_video, verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='vivienda_gallery',
            name='actualizacion',
            field=models.DateField(auto_now=True, verbose_name='Actualizaci\xf3n'),
        ),
    ]
