# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0020_auto_20181004_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='actualizacion',
            field=models.DateField(auto_now=True, verbose_name='Actualizaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='publicacion',
            field=models.DateField(auto_now_add=True, verbose_name='Publicaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='vivienda_gallery',
            name='publicacion',
            field=models.DateField(auto_now_add=True, verbose_name='Publicaci\xf3n'),
        ),
    ]
