# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import viviendas.models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0022_auto_20181004_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='altitud',
            field=models.CharField(blank=True, default='None', max_length=255, verbose_name='Altitud'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='antiguedad',
            field=models.DateField(blank=True, max_length=255, verbose_name='Antig\xfcedad'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='banos',
            field=models.IntegerField(blank=True, verbose_name='Ba\xf1os'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='dormitorios',
            field=models.IntegerField(blank=True, verbose_name='Dormitorios'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='eficiencia',
            field=models.CharField(blank=True, default='None', max_length=255, verbose_name='Eficiencia'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='galeria',
            field=models.ManyToManyField(blank=True, to='viviendas.Vivienda_gallery', verbose_name='Im\xe1genes de galer\xeda'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=viviendas.models.custom_upload_to_vivienda, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='latitud',
            field=models.CharField(blank=True, default='None', max_length=255, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='operacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Operaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='precio',
            field=models.IntegerField(blank=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='superficie',
            field=models.FloatField(blank=True, verbose_name='Superficie'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ubicaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='vivienda_gallery',
            name='imagen_gallery',
            field=models.ImageField(blank=True, upload_to=viviendas.models.custom_upload_to_gallery, verbose_name='Imagen de galer\xeda'),
        ),
    ]
