# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import viviendas.models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0023_auto_20181004_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda_gallery',
            name='imagen_gallery',
            field=models.ImageField(upload_to=viviendas.models.custom_upload_to_gallery, verbose_name='Imagen de galer\xeda'),
        ),
    ]
