# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0026_auto_20181014_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='vivienda',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ciudad'),
        ),
    ]
