# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0028_auto_20181023_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='galeria',
            field=models.ManyToManyField(blank=True, to='viviendas.Vivienda_gallery', verbose_name='Im\xe1genes de galer\xeda'),
        ),
    ]
