# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0030_auto_20181023_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='aseos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aseos'),
        ),
    ]
