# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import viviendas.models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0031_vivienda_aseos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vivienda',
            options={'ordering': ['-publicacion'], 'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AlterModelOptions(
            name='vivienda_gallery',
            options={'ordering': ['-publicacion'], 'verbose_name': 'Galer\xeda de propiedad', 'verbose_name_plural': 'Galer\xedas de propiedades'},
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Propiedad destacada'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='planos',
            field=models.FileField(blank=True, default='', upload_to=viviendas.models.custom_upload_to_planos, verbose_name='Planos de propiedad (PDF) (M\xe1x. 10MB)'),
        ),
    ]
